// Problem 2: Even Fibonacci Numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

function fiboEvenSum(n) {
  // declare variables to store
  let previous = 1;
  let current = 2;
  let sum = 0;
  // loop through fibonacci sequence
  while (current <= n) {
    // check if current is even
    if (current % 2 === 0) {
      // add to sum
      sum += current;
    }
    // update previous and current
    let next = current;
    current += previous;
    previous = next;
  }
  // return sum
  return sum;
}